### PR TITLE
Convert project to Swift 3

### PR DESCRIPTION
**Pull request by potmo**

### CODE REVIEW

**Comment by potmo** [comment]
☝️ fails since Jenkins wants the project to be a Swift 2.3 project

**Comment by jonreid** [comment]
So close! Just a little more to make Travis happy

**Comment by potmo** [comment]
can someone that knows travis please help out on this branch?

**Comment by jcummings2** [comment]
this branch is working well for me locally.

**Comment by jonreid** [comment]
@potmo Travis configuration is saved in `.travis.yml`. It's running and passing tests. But it's failing when running `pod lib lint` because CocoaPods is reporting warnings. So it looks like all that's left is to fix those warnings. Try running `pod lib lint` locally.

**Comment by jonreid** [comment]
Let me know if I can be of further help.

**Comment by potmo** [comment]
@jonreid I don't understand what the problem is. Do you think you can have a look at it?

**Comment by jonreid** [comment]
Appreciate your efforts @potmo! Looks like #21 takes care of things.

**Comment by potmo** [comment]
I'll close this PR in favour of #21

**Pull request closed without merging**
