### PR TITLE
converted to Swift-3

### PR DESCRIPTION
**Pull request by renep**
I have migrated the project to Swift 3 and I have tested the commands from the .travis.yml

I have started from scratch and not used the current open pull request #20 

I also tried to solve all warnings and I hope I have not missed something ;-)

### CODE REVIEW

**Comment by jonreid** [comment]
@nschum  I suggest making a `swift-2.3` branch at 73f1f10

**Comment by potmo** [comment]
Lets go ahead and merge this and push a new Pod

**Comment by jonreid** [comment]
(Eagerly awaiting merge)

**Comment by renep** [comment]
Hmm, @nschum is not responding, I have also wrote a mail to @nschum but I got no reply.

Any suggestions?

**Comment by potmo** [comment]
Any news on this @nschum ?

**Comment by nschum** [comment]
Sorry guys, I started a new job and have been busy. But we released this week so I expect to have a bit more time now.

I'm going through issues and PRs right now.

**Comment by nschum** [comment]
Thank you @renep.
Merged and I will bump the version number tomorrow unless problems become clear.

**Comment by jonreid** [comment]
Congratulations on the new job @nschum!

**Pull request closed without merging**
