### PR TITLE
Enable more SwiftFormat rules

### PR DESCRIPTION
**Pull request by jonreid**
- blankLinesAtEndOfScope
- blankLinesBetweenScopes
- consecutiveBlankLines
- linebreakAtEndOfFile
- semicolons
- trailingSpace

### CODE REVIEW

**Comment by jonreid** [comment]
@renep, Coveralls wasn't able to comment on this PR. Do you have permission to change Settings -> Authorized OAuth apps to add Coveralls? If not we may need @nschum to add https://coveralls.io/github/nschum/SwiftHamcrest

**Comment by renep** [comment]
No I have not the access rights. I'll try to get in touch with @nschum .

**Comment by jonreid** [comment]
Friendly ping. I think getting this data is important for all future changes.

**Comment by jonreid** [comment]
It's been too long. I'm going to repeat this change in case

- swiftformat wants to do anything different
- source files have been updated
- Maybe Coveralls will comment on a fresh PR? Let's see

**Pull request closed without merging**
